#!/bin/bash
# On a new computer, you need to make sure to execute
# python setup.py register

# Basic upload command:
python setup.py sdist --formats 'zip,gztar' bdist bdist_dumb bdist_wininst upload
